server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/station_search
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: station
    password: station_password