@baseUrl = http://localhost:8080
@countryCode = ES
@productType = DIESEL_A

### 1. Find the administrative hierarchy using the location catalogue
GET {{baseUrl}}/locations/search?countryCode={{countryCode}}&query=Ardales&limit=10
Accept: application/json

### 2. Country-wide current statistics (administrative areas omitted)
GET {{baseUrl}}/statistics/fuel-prices/current?countryCode={{countryCode}}&productType={{productType}}
Accept: application/json

### 3. Current statistics for Ardales
GET {{baseUrl}}/statistics/fuel-prices/current?countryCode={{countryCode}}&productType={{productType}}&adminArea1=Andalucía&adminArea2=Málaga&adminArea3=Ardales
Accept: application/json

### 4. Historical statistics for Ardales
GET {{baseUrl}}/statistics/fuel-prices/history?countryCode={{countryCode}}&productType={{productType}}&adminArea1=Andalucía&adminArea2=Málaga&adminArea3=Ardales&from=2026-09-01&to=2026-09-24
Accept: application/json

### 5. Rank all localities in the country
GET {{baseUrl}}/statistics/fuel-prices/localities?countryCode={{countryCode}}&productType={{productType}}
Accept: application/json

### 6. Rank localities filtered by administrative metadata
GET {{baseUrl}}/statistics/fuel-prices/localities?countryCode={{countryCode}}&productType={{productType}}&adminArea2=Málaga
Accept: application/json

### 7. Current statistics for an admin_area_2
GET {{baseUrl}}/statistics/fuel-prices/current?countryCode={{countryCode}}&productType={{productType}}&adminArea1=Andalucía&adminArea2=Málaga
Accept: application/json

### 8. Historical statistics for an admin_area_2
GET {{baseUrl}}/statistics/fuel-prices/history?countryCode={{countryCode}}&productType={{productType}}&adminArea1=Andalucía&adminArea2=Málaga&from=2026-09-01&to=2026-09-24
Accept: application/json
